# Docker Buildfile for ComfyUI to use a RX570 / Polaris / gfx803 AMD GPU with ROCm 6.3.4
# created, build and compiled by Robert Rosenbusch at December 2024 / May 2025

### Build rocm64_gfx803_base:6.4 first! Read the README.md, it could save lifetime :P
FROM rocm64_gfx803_pytorch:2.6

SHELL ["/bin/bash", "-c"]  
ENV COMFYUI_PORT=8188 \
    DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1 \
    PYTHONENCODING==UTF-8 \
    REQS_FILE='requirements.txt' \
    COMMANDLINE_ARGS='' \
    PIP_ROOT_USER_ACTION='ignore' 

RUN dpkg -r --force-depends python3-wheel python3-xyz && \
    pip install --break-system-packages cmake mkl mkl-include && \
    pip install --break-system-packages --upgrade wheel && \
    true

### Install PyRSMI to monitore the GPU via ComfyUI-Crystools    
RUN git clone https://github.com/ROCm/pyrsmi /pyrsmi && \
    true

WORKDIR /pyrsmi
RUN python3 -m pip install --break-system-packages -e . && \
    true

### Install and Compile ComfyUI, reinstall pytorch and torchvision WHL Files    
WORKDIR /    
RUN git clone https://github.com/comfyanonymous/ComfyUI.git /ComfyUI && \
    true

WORKDIR /ComfyUI
RUN python3 -m venv venv && \
    ./venv/bin/python3 -m pip install --break-system-packages --upgrade pip && \
    ./venv/bin/pip install --break-system-packages psutil && \
    ./venv/bin/pip install --break-system-packages -r requirements.txt && \
    ./venv/bin/pip uninstall --break-system-packages -y torch torchvision torchaudio && \    
    ./venv/bin/pip install --break-system-packages /pytorch/dist/*.whl && \
    ./venv/bin/pip install --break-system-packages /vision/dist/*.whl && \
    ./venv/bin/pip install --break-system-packages /audio/dist/*.whl && \
    ./venv/bin/python3 -m pip install --break-system-packages -e /pyrsmi/. && \
    ./venv/bin/python3 -m pip uninstall --break-system-packages numpy -y && \
    ./venv/bin/pip install --break-system-packages numpy==1.26.4 && \
    true    

### Install ComfyUI Manager    
WORKDIR /ComfyUI/custom_nodes
RUN git clone https://github.com/ltdrdata/ComfyUI-Manager.git &&\
    true

### Install PyRSMI to ComfyUI-Environment
WORKDIR /ComfyUI    

RUN pip install --break-system-packages psutil && \
    ./venv/bin/pip install --break-system-packages -e /pyrsmi && \
    true

### Create a best practice Shell Script to start ComfyUI    
RUN touch comfi.sh && \
    echo "#!/bin/bash" >> comfi.sh && \
    ### with redirected LogFile    
    #echo "MIOPEN_LOG_LEVEL=3 TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1  PYTORCH_TUNABLEOP_ENABLED=0  ./venv/bin/python main.py --listen --lowvram --port ${COMFYUI_PORT}  >> /comfy/comfy_rocm64_pt26.log 2>&1" > comfi.sh && \
    ### Use "--lowvram" to get a correct output
    echo "MIOPEN_LOG_LEVEL=3 TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1  PYTORCH_TUNABLEOP_ENABLED=0  ./venv/bin/python main.py --listen --lowvram --port ${COMFYUI_PORT} " >> comfi.sh && \
    chmod +x comfi.sh && \
    true    

EXPOSE ${COMFYUI_PORT}
CMD ["bash","/ComfyUI/comfi.sh"]
